import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { UserContextProvider } from "./context";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Chatgpt Replica",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} ${process.env.NODE_ENV==="development" && 'border-red-600 border-solid border-8'}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <UserContextProvider>
          {children}
          </UserContextProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
